# roles/zabbix-agent/tasks/main.yml
# Install and configure Zabbix agent
---
- name: Ensure policy that policycoreutils-python is installed
  yum:
    name: ['policycoreutils-python', 'firewalld', 'python-firewall']
    state: installed

- name: Install Zabbix repo CentOS 7
  yum: 
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm
    state: installed
  when: ansible_distribution_major_version == "7"

- name: Install Zabbix agent
  yum: 
    name: zabbix-agent
    state: installed

- name: Create Zabbix agent configuration file 
  template: 
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    group: root
    owner: root
    mode: '0644'
  notify: restart zabbix-agent

- name: CentOS 7 Specific tasks
  block:
  - name: Copy sudeoers config
    copy: 
      src: zabbix_sudoers_systemd
      dest: /etc/sudoers.d/zabbix_sudoers_systemd
      owner: root
      group: root
      mode: '0644'
  - name: Copy Zabbix agent config file to add systemd service user parameters
    copy: 
      src: userparameter_systemd_services.conf
      dest: /etc/zabbix/zabbix_agentd.d/userparameter_systemd_services.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart zabbix-agent
  - name: Copy Zabbix systemd service discovery script
    copy: 
      src: zabbix_systemd_service_discovery.sh
      dest: /usr/local/bin/zabbix_systemd_service_discovery.sh
      owner: root
      group: root
      mode: '0655'
    notify: restart zabbix-agent
  - name: Copy Zabbix systemd service restart check script
    copy: 
      src: zabbix_systemd_service_restart_check.sh
      dest: /usr/local/bin/zabbix_systemd_service_restart_check.sh
      owner: root
      group: root
      mode: '0655'
    notify: restart zabbix-agent
  - name: Enable zabbix_run_sudo SELinux boolean
    seboolean:
      name: zabbix_run_sudo
      state: yes
      persistent: yes
    notify: restart zabbix-agent
  - name: Open Zabbix Agent port in firewall 
    firewalld:
      port: 10050/tcp
      permanent: yes
      state: enabled
    notify: reload firewall
  when: ansible_distribution_major_version == "7" 

- name: CentOS 6 specific tasks
  block: 
  - name: Copy sudeoers config
    copy: 
      src: zabbix_sudoers_upstart
      dest: /etc/sudoers.d/zabbix_sudoers_upstart
      owner: root
      group: root
      mode: '0644'
  - name: Copy Zabbix agent config file to add upstart service user parameters
    copy:
      src: zabbix_upstart_services.conf
      dest: /etc/zabbix/zabbix_agentd.d/zabbix_upstart_services.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart zabbix-agent
  - name: Copy Zabbix upstart service discovery script
    copy: 
      src: zabbix_upstart_service_discovery.sh
      dest: /usr/local/bin/zabbix_upstart_service_discovery.sh
      owner: root
      group: root
      mode: '0755'
  when: ansible_distribution_major_version == "6"

- name: Change the zabbix_agent_t SELinux domain to permissive
  selinux_permissive:
    name: zabbix_agent_t
    permissive: true
  notify: restart zabbix-agent

- name: Enable zabbix-agent service
  service: 
    name: zabbix-agent
    enabled: true